# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Linuxctl < Formula
  desc "Declarative Linux host configuration — plan, apply, verify, rollback."
  homepage "https://github.com/itunified-io/linuxctl"
  version "2026.04.11.8"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/itunified-io/linuxctl/releases/download/v2026.04.11.8/linuxctl_2026.04.11.8_darwin_amd64.tar.gz"
      sha256 "e289537684bb353ff288e80ee6407f77fe2ab93e96a622267f81b6fd2096905c"

      define_method(:install) do
        bin.install "linuxctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/itunified-io/linuxctl/releases/download/v2026.04.11.8/linuxctl_2026.04.11.8_darwin_arm64.tar.gz"
      sha256 "19ef1848917f9bae92e8c828d65061718253388c7eb44f4286f28305fc169445"

      define_method(:install) do
        bin.install "linuxctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/itunified-io/linuxctl/releases/download/v2026.04.11.8/linuxctl_2026.04.11.8_linux_amd64.tar.gz"
      sha256 "11162920800a03acb9cac850319b91e9bfb3f6931f84e764de1e200dbcba7001"
      define_method(:install) do
        bin.install "linuxctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itunified-io/linuxctl/releases/download/v2026.04.11.8/linuxctl_2026.04.11.8_linux_arm64.tar.gz"
      sha256 "591c3ca2ecaa9bf41df1a77a27afa6ee425a3ed7aa1708a47dc02aa9514f37f4"
      define_method(:install) do
        bin.install "linuxctl"
      end
    end
  end
end
