# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Proxctl < Formula
  desc "Proxmox VM provisioning CLI — kickstart, lifecycle, workflows"
  homepage "https://github.com/itunified-io/proxctl"
  version "2026.05.04.4"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/itunified-io/proxctl/releases/download/v2026.05.04.4/proxctl_2026.05.04.4_darwin_amd64.tar.gz"
      sha256 "d60d8d9949cb5d98a90bad9e743e8148eb978550973aef02b85b268b6b95252c"

      define_method(:install) do
        bin.install "proxctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/itunified-io/proxctl/releases/download/v2026.05.04.4/proxctl_2026.05.04.4_darwin_arm64.tar.gz"
      sha256 "685343fe6fbf0225f5fa1a597f2a92d692341a4b42b24e36e6d556207865ca21"

      define_method(:install) do
        bin.install "proxctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/itunified-io/proxctl/releases/download/v2026.05.04.4/proxctl_2026.05.04.4_linux_amd64.tar.gz"
      sha256 "75c454649d975613b0acba6a16331d96cee0cfec9cc5151d9ff424da693f5ffe"
      define_method(:install) do
        bin.install "proxctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itunified-io/proxctl/releases/download/v2026.05.04.4/proxctl_2026.05.04.4_linux_arm64.tar.gz"
      sha256 "0f18123295e6f062804270d37b97d52e21dbb7e98a9cde7e1af740fdfe32252a"
      define_method(:install) do
        bin.install "proxctl"
      end
    end
  end
end
